version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root  # ← สำคัญมาก!
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    
    depends_on:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins_home:
